### ISSUE TITLE
Special characters are not being handled

### ISSUE THREAD

**Issue by Womo2** [yamautomate/PowerShell-OpenAI-API-Wrapper#2]
Special characters like German umlauts (ä ü ö ...) and French accents (á à ...)
cause an error message when entered and are not displayed correctly in responses.

**Comment by yamautomate** [comment]
Many thanks for your report! 
This is fixed in 1.3 by simply replacing the umlauts (and some other special characters the API does not like) with their equivalents. If you want to, you can grab the module from the 1.3 branch. I will release it once I updated the documentation accordignly. Please note: The module name is different and also the functions got renamed.

**Comment by yamautomate** [comment]
Reopen: I don‘t catch the french accents.

**Comment by yamautomate** [comment]
Fixed in 1.3.2 by encoding properly. However, in prompts and export the special characters are replaced by "?" because its still not done properly.
    $bytes = $iso.GetBytes($query)
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($query)
    $query = [System.Text.Encoding]::utf8.GetString($bytes)

**Comment by Womo2** [comment]
Der folgende Teil dieser Nachricht enthält einen Anhang im
sogenannten Internet MIME Nachrichtenformat.
Wenn Sie Pegasus Mail oder ein beliebiges anderes MIME-kompatibles
Email-System verwenden, sollten Sie den Anhang mit Ihrem Email-System
speichern oder anzeigen können. Gegebenenfalls fragen Sie Ihren Administrator.

The following section of this message contains a file attachment
prepared for transmission using the Internet MIME message format.
If you are using Pegasus Mail, or any another MIME-compliant system,
you should be able to save it or view it from within your mailer.
If you cannot, please ask your system administrator for assistance.

   ---- Datei Information/File information -----------
     Datei/File:  hts_1.PNG
     Datum/Date:  17 Apr 2023, 22:31
     Größe/Size:  134166 bytes.
     Typ/Type:    Unbekannt

Der folgende Teil dieser Nachricht enthält einen Anhang im
sogenannten Internet MIME Nachrichtenformat.
Wenn Sie Pegasus Mail oder ein beliebiges anderes MIME-kompatibles
Email-System verwenden, sollten Sie den Anhang mit Ihrem Email-System
speichern oder anzeigen können. Gegebenenfalls fragen Sie Ihren Administrator.

The following section of this message contains a file attachment
prepared for transmission using the Internet MIME message format.
If you are using Pegasus Mail, or any another MIME-compliant system,
you should be able to save it or view it from within your mailer.
If you cannot, please ask your system administrator for assistance.

   ---- Datei Information/File information -----------
     Datei/File:  DEFAULT.BMP
     Datum/Date:  21 Sep 2001, 14:59
     Größe/Size:  358 bytes.
     Typ/Type:    Unbekannt
